import 'package:signal_scope/src/core/errors/app_error.dart';

final Map<String, AppError> errorCatalog = <String, AppError>{
  'PLATFORM_NOT_SUPPORTED': const AppError(
    code: 'PLATFORM_NOT_SUPPORTED',
    userMessage: 'Funcion no disponible en esta plataforma.',
    technicalMessage: 'The current platform does not expose the requested capability.',
    recoverable: false,
    suggestedAction: 'Usa Android para las funciones de medicion real.',
    shouldLog: false,
    severity: ErrorSeverity.warning,
    module: 'core',
  ),
  'PERMISSION_DENIED': const AppError(
    code: 'PERMISSION_DENIED',
    userMessage: 'Se necesita permiso para continuar con esta medicion.',
    technicalMessage: 'Runtime permission denied by the user.',
    recoverable: true,
    suggestedAction: 'Solicita el permiso desde la pantalla principal.',
    shouldLog: true,
    severity: ErrorSeverity.warning,
    module: 'permissions',
  ),
  'CELLULAR_PERMISSION_DENIED': const AppError(
    code: 'CELLULAR_PERMISSION_DENIED',
    userMessage: 'No se pudo leer la senal celular porque falta permiso.',
    technicalMessage: 'READ_PHONE_STATE not granted.',
    recoverable: true,
    suggestedAction: 'Concede el permiso de telefono.',
    shouldLog: true,
    severity: ErrorSeverity.warning,
    module: 'cellular',
  ),
  'WIFI_DISABLED': const AppError(
    code: 'WIFI_DISABLED',
    userMessage: 'Activa el Wi-Fi para buscar redes cercanas.',
    technicalMessage: 'WifiManager.isWifiEnabled returned false.',
    recoverable: true,
    suggestedAction: 'Enciende el Wi-Fi desde ajustes rapidos o configuracion.',
    shouldLog: false,
    severity: ErrorSeverity.info,
    module: 'wifi',
  ),
  'BLUETOOTH_DISABLED': const AppError(
    code: 'BLUETOOTH_DISABLED',
    userMessage: 'El Bluetooth esta apagado.',
    technicalMessage: 'BluetoothAdapter is disabled.',
    recoverable: true,
    suggestedAction: 'Activa Bluetooth para iniciar una sesion BLE.',
    shouldLog: false,
    severity: ErrorSeverity.info,
    module: 'bluetooth',
  ),
  'USB_HOST_NOT_SUPPORTED': const AppError(
    code: 'USB_HOST_NOT_SUPPORTED',
    userMessage: 'Este dispositivo no soporta USB Host.',
    technicalMessage: 'PackageManager.FEATURE_USB_HOST is absent.',
    recoverable: false,
    suggestedAction: 'Usa otro dispositivo o limita la app al modo interno.',
    shouldLog: false,
    severity: ErrorSeverity.warning,
    module: 'sdr',
  ),
};
